# Início
Trabalho de implementação do GLPI via máquina virtual para a disciplina de Administração de TI.

## Finalidades
Controlar toda a vida acadêmica por meio do GLPI, incluindo chamados, ferramentas utilizadas, computadores e atividades a serem resolvidas.

## Implementação
Aqui está o uso do meu GLPI com dashboards em tempo real e acompanhamento de todas as tarefas.
